# Generated by Django 4.2.30 on 2026-08-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Summary',
        ),
    ]
