# Generated by Django 4.2.30 on 2026-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('Desc', models.TextField()),
                ('Price', models.TextField()),
                ('Summary', models.TextField()),
            ],
        ),
    ]
